"""
Multi-Timeframe FVG Analysis Engine.

Implements hierarchical FVG detection across multiple timeframes:
  1H -> 15M -> 5M -> 1M

Rules:
- FVGs are detected on each timeframe independently.
- Higher timeframe FVGs carry more weight (higher confluence score).
- Entry is ONLY allowed on timeframes <= 15M (15M, 5M, 1M).
- Entry signal: price completely breaks through an FVG (full traversal).
- An FVG is invalidated when price completely breaks through it.
- Lower timeframe FVGs contained within a higher TF FVG zone have
  increased confluence score (nested FVG confirmation).

The engine produces a ranked list of FVG-based entry signals with
confluence scores for the strategy to act upon.
"""
import os
import sys
from typing import List, Dict, Optional, Tuple
from dataclasses import dataclass, field
from enum import Enum

import pandas as pd
import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from indicators.fvg import (
    FVGType, FVGStatus, FairValueGap, FVGTracker,
    detect_fvgs, filter_significant_fvgs,
)
from config.settings import (
    MULTI_TF_FVG_TIMEFRAMES,
    MULTI_TF_FVG_WEIGHTS,
    FVG_MULTI_TF_CONFIGS,
    ENTRY_TIMEFRAMES,
)


# =============================================================================
# Data Structures
# =============================================================================
@dataclass
class MultiTFFVG:
    """
    An FVG enriched with multi-timeframe context.

    Attributes
    ----------
    fvg : FairValueGap
        The underlying FVG object.
    timeframe : str
        Timeframe where this FVG was detected.
    weight : float
        Base weight from timeframe hierarchy.
    confluence_score : float
        Computed confluence score considering nesting within higher TF FVGs.
    nested_in : list
        List of higher-TF FVGs that contain this one.
    decision_fvg : bool
        True if this FVG was used in a trade entry/exit decision.
    """
    fvg: FairValueGap
    timeframe: str
    weight: float = 1.0
    confluence_score: float = 0.0
    nested_in: list = field(default_factory=list)
    decision_fvg: bool = False

    @property
    def top(self) -> float:
        return self.fvg.top

    @property
    def bottom(self) -> float:
        return self.fvg.bottom

    @property
    def midpoint(self) -> float:
        return self.fvg.midpoint

    @property
    def size(self) -> float:
        return self.fvg.size

    @property
    def fvg_type(self) -> FVGType:
        return self.fvg.fvg_type

    @property
    def status(self) -> FVGStatus:
        return self.fvg.status

    @property
    def is_active(self) -> bool:
        return self.fvg.is_active

    @property
    def timestamp(self) -> pd.Timestamp:
        return self.fvg.timestamp

    def to_dict(self) -> dict:
        """Serialize for MongoDB storage and frontend display."""
        return {
            "timeframe": self.timeframe,
            "fvg_type": self.fvg.fvg_type.value,
            "top": float(self.fvg.top),
            "bottom": float(self.fvg.bottom),
            "midpoint": float(self.fvg.midpoint),
            "size": float(self.fvg.size),
            "timestamp": str(self.fvg.timestamp),
            "status": self.fvg.status.value,
            "weight": float(self.weight),
            "confluence_score": float(self.confluence_score),
            "nested_in_count": len(self.nested_in),
            "decision_fvg": self.decision_fvg,
        }


@dataclass
class EntrySignal:
    """
    A potential entry signal generated by the multi-TF FVG engine.

    An entry is triggered when price completely breaks through an FVG
    on a timeframe <= 15M.
    """
    timeframe: str
    direction: str  # "long" or "short"
    broken_fvg: MultiTFFVG  # The FVG that was broken (entry trigger)
    protective_fvg: Optional[MultiTFFVG]  # Nearest FVG for SL placement
    confluence_score: float  # Combined score from nested FVGs
    entry_price: float
    timestamp: pd.Timestamp

    def to_dict(self) -> dict:
        return {
            "timeframe": self.timeframe,
            "direction": self.direction,
            "entry_price": float(self.entry_price),
            "confluence_score": float(self.confluence_score),
            "broken_fvg": self.broken_fvg.to_dict(),
            "protective_fvg": self.protective_fvg.to_dict() if self.protective_fvg else None,
            "timestamp": str(self.timestamp),
        }


# =============================================================================
# Multi-Timeframe FVG Analyzer
# =============================================================================
class MultiTFAnalyzer:
    """
    Analyzes FVGs across multiple timeframes hierarchically.

    Timeframes analyzed (in order of weight):
      1H (weight=4) > 15M (weight=3) > 5M (weight=2) > 1M (weight=1)

    The analyzer:
    1. Detects FVGs on each timeframe independently.
    2. Checks for nesting (lower-TF FVG inside higher-TF FVG zone).
    3. Computes confluence scores.
    4. Tracks FVG invalidation (price breaks completely through).
    5. Generates entry signals when FVGs break on entry timeframes.
    """

    def __init__(self, fvg_configs: dict = None):
        # Per-TF config (allows dashboard sliders to override detection params)
        self.fvg_configs = fvg_configs if fvg_configs is not None else FVG_MULTI_TF_CONFIGS

        # Separate tracker per timeframe
        self.trackers: Dict[str, FVGTracker] = {}
        for tf in MULTI_TF_FVG_TIMEFRAMES:
            self.trackers[tf] = FVGTracker()

        # All multi-TF FVGs (enriched with context)
        self.all_multi_tf_fvgs: List[MultiTFFVG] = []

        # Entry signals generated
        self.entry_signals: List[EntrySignal] = []

        # Previously broken FVGs (for entry detection)
        self._prev_broken_ids: set = set()
        self._known_fvg_keys: set = set()

    @staticmethod
    def _fvg_key(timeframe: str, fvg: FairValueGap) -> tuple:
        """Stable key for de-duplication and signal tracking."""
        return (
            timeframe,
            fvg.fvg_type.value,
            round(float(fvg.top), 4),
            round(float(fvg.bottom), 4),
            str(fvg.timestamp),
        )

    def detect_fvgs_for_timeframe(
        self,
        df: pd.DataFrame,
        timeframe: str,
        current_price: float = None,
    ) -> List[MultiTFFVG]:
        """
        Detect FVGs on a single timeframe and wrap them as MultiTFFVG.

        Parameters
        ----------
        df : pd.DataFrame
            OHLCV data for this timeframe.
        timeframe : str
            Timeframe identifier ('1h', '15m', '5m', '1m').
        current_price : float, optional
            Current price for filtering by proximity.

        Returns
        -------
        List[MultiTFFVG]
            Newly detected FVGs enriched with TF context.
        """
        if timeframe not in MULTI_TF_FVG_TIMEFRAMES:
            return []

        config = self.fvg_configs.get(timeframe, FVG_MULTI_TF_CONFIGS.get(timeframe, {}))
        weight = MULTI_TF_FVG_WEIGHTS.get(timeframe, 1.0)

        # Slice df to per-TF lookback window (time-based, configurable from dashboard)
        lookback_bars = config.get("lookback_bars")
        if lookback_bars is not None and len(df) > lookback_bars:
            df = df.iloc[-lookback_bars:]

        # Detect raw FVGs
        raw_fvgs = detect_fvgs(df, timeframe=timeframe)

        # Filter significant ones
        if current_price is not None and raw_fvgs:
            filtered = filter_significant_fvgs(
                raw_fvgs,
                current_price=current_price,
                max_fvgs=config.get("max_fvgs", 4),
                search_range_points=config.get("search_range_points", 400),
                min_size_percentile=config.get("min_size_percentile", 0.30),
            )
        else:
            filtered = raw_fvgs

        # Add to tracker
        self.trackers[timeframe].add_fvgs(filtered)

        # Wrap as MultiTFFVG
        new_multi = []
        for fvg in filtered:
            fvg_key = self._fvg_key(timeframe, fvg)
            if fvg_key in self._known_fvg_keys:
                continue
            self._known_fvg_keys.add(fvg_key)

            mt_fvg = MultiTFFVG(
                fvg=fvg,
                timeframe=timeframe,
                weight=weight,
                confluence_score=weight,  # Base score = weight
            )
            new_multi.append(mt_fvg)

        self.all_multi_tf_fvgs.extend(new_multi)
        if new_multi:
            self._compute_nesting()
        return new_multi

    def analyze_all_timeframes(
        self,
        data_dict: Dict[str, pd.DataFrame],
        current_price: float = None,
    ) -> List[MultiTFFVG]:
        """
        Run FVG detection on all available timeframes.

        Parameters
        ----------
        data_dict : dict
            Keys are timeframe strings, values are OHLCV DataFrames.
        current_price : float, optional
            Current market price for proximity filtering.

        Returns
        -------
        List[MultiTFFVG]
            All detected FVGs across all timeframes.
        """
        all_new = []
        for tf in MULTI_TF_FVG_TIMEFRAMES:
            if tf in data_dict and not data_dict[tf].empty:
                new_fvgs = self.detect_fvgs_for_timeframe(
                    data_dict[tf], tf, current_price
                )
                all_new.extend(new_fvgs)

        # Compute nesting relationships and update confluence scores
        self._compute_nesting()

        return all_new

    def update_states(
        self,
        candle_high: float,
        candle_low: float,
        candle_close: float,
        timeframe: str = None,
    ):
        """
        Update FVG states with new price data.

        If timeframe is specified, only update that tracker.
        Otherwise, update all trackers.
        """
        if timeframe:
            if timeframe in self.trackers:
                self.trackers[timeframe].update(
                    candle_high, candle_low, candle_close
                )
        else:
            for tf, tracker in self.trackers.items():
                tracker.update(candle_high, candle_low, candle_close)

        # Update multi-TF FVG status from underlying trackers
        for mt_fvg in self.all_multi_tf_fvgs:
            # Status is already synced via the FairValueGap reference
            pass

    def check_for_entry_signals(
        self,
        candle_high: float,
        candle_low: float,
        candle_close: float,
        current_price: float,
        timestamp: pd.Timestamp,
    ) -> List[EntrySignal]:
        """
        Check if any FVG breakouts on entry timeframes generate signals.

        Entry logic:
        - A BEARISH FVG breaks (price closes above its top) -> LONG signal
          (price has broken above supply, momentum is up)
        - A BULLISH FVG breaks (price closes below its bottom) -> SHORT signal
          (price has broken below demand, momentum is down)

        Only FVGs on ENTRY_TIMEFRAMES (15M, 5M, 1M) generate entries.

        Returns
        -------
        List[EntrySignal]
            New entry signals (empty if none).
        """
        signals = []

        # First update all states
        self.update_states(candle_high, candle_low, candle_close)

        # Find newly broken FVGs on entry timeframes
        for mt_fvg in self.all_multi_tf_fvgs:
            fvg_id = self._fvg_key(mt_fvg.timeframe, mt_fvg.fvg)

            if mt_fvg.timeframe not in ENTRY_TIMEFRAMES:
                continue

            if mt_fvg.fvg.status != FVGStatus.BROKEN:
                continue

            if fvg_id in self._prev_broken_ids:
                continue  # Already processed

            self._prev_broken_ids.add(fvg_id)

            # Determine direction from FVG break
            if mt_fvg.fvg_type == FVGType.BEARISH:
                # Bearish FVG broken upward -> LONG
                direction = "long"
            elif mt_fvg.fvg_type == FVGType.BULLISH:
                # Bullish FVG broken downward -> SHORT
                direction = "short"
            else:
                continue

            # Find protective FVG
            protective = self._find_protective_fvg(current_price, direction, mt_fvg.timeframe)

            signal = EntrySignal(
                timeframe=mt_fvg.timeframe,
                direction=direction,
                broken_fvg=mt_fvg,
                protective_fvg=protective,
                confluence_score=mt_fvg.confluence_score,
                entry_price=current_price,
                timestamp=timestamp,
            )
            signals.append(signal)

            # Mark as decision FVG
            mt_fvg.decision_fvg = True

        # Sort by confluence score (highest first)
        signals.sort(key=lambda s: s.confluence_score, reverse=True)

        self.entry_signals.extend(signals)
        return signals

    def _compute_nesting(self):
        """
        Compute nesting relationships between FVGs.

        A lower-TF FVG is "nested" in a higher-TF FVG if its price range
        is completely contained within the higher-TF FVG's range.

        Nested FVGs receive a confluence bonus:
          confluence_score = base_weight + sum(parent_weights * 0.5)
        """
        # Group by timeframe
        by_tf: Dict[str, List[MultiTFFVG]] = {}
        for mt in self.all_multi_tf_fvgs:
            by_tf.setdefault(mt.timeframe, []).append(mt)

        tf_order = MULTI_TF_FVG_TIMEFRAMES  # ['1h', '15m', '5m', '1m']

        for i, lower_tf in enumerate(tf_order):
            if lower_tf not in by_tf:
                continue
            for mt_lower in by_tf[lower_tf]:
                if not mt_lower.is_active:
                    continue

                # Check against all higher timeframes
                for j in range(0, i):
                    higher_tf = tf_order[j]
                    if higher_tf not in by_tf:
                        continue

                    for mt_higher in by_tf[higher_tf]:
                        if not mt_higher.is_active:
                            continue

                        # Check containment: lower FVG range within higher FVG range
                        if (mt_lower.bottom >= mt_higher.bottom and
                                mt_lower.top <= mt_higher.top):
                            if mt_higher not in mt_lower.nested_in:
                                mt_lower.nested_in.append(mt_higher)

                # Recompute confluence score
                mt_lower.confluence_score = mt_lower.weight
                for parent in mt_lower.nested_in:
                    # Bonus: 50% of parent weight for each nesting level
                    mt_lower.confluence_score += parent.weight * 0.5

    def _find_protective_fvg(
        self,
        price: float,
        direction: str,
        preferred_tf: str = None,
    ) -> Optional[MultiTFFVG]:
        """
        Find the nearest active FVG suitable for stop-loss placement.

        For LONG: find nearest active Bullish FVG below price (SL below it).
        For SHORT: find nearest active Bearish FVG above price (SL above it).

        Prefers higher-timeframe FVGs for stronger protection.
        """
        candidates = []

        for mt in self.all_multi_tf_fvgs:
            if not mt.is_active:
                continue

            if direction == "long":
                if mt.fvg_type == FVGType.BULLISH and mt.top <= price:
                    dist = price - mt.top
                    candidates.append((mt, dist))
            elif direction == "short":
                if mt.fvg_type == FVGType.BEARISH and mt.bottom >= price:
                    dist = mt.bottom - price
                    candidates.append((mt, dist))

        if not candidates:
            return None

        # Sort by: weight (descending), then distance (ascending)
        candidates.sort(key=lambda x: (-x[0].weight, x[1]))
        return candidates[0][0]

    def get_active_fvgs(self, timeframe: str = None) -> List[MultiTFFVG]:
        """Get all active FVGs, optionally filtered by timeframe."""
        result = [mt for mt in self.all_multi_tf_fvgs if mt.is_active]
        if timeframe:
            result = [mt for mt in result if mt.timeframe == timeframe]
        return result

    def get_all_fvgs_for_display(self) -> List[dict]:
        """
        Get all FVGs (active and broken) as dicts for frontend display.
        Used by the visual backtesting chart to render FVG zones.
        """
        return [mt.to_dict() for mt in self.all_multi_tf_fvgs]

    def get_decision_fvgs(self) -> List[dict]:
        """Get only FVGs that influenced trade decisions."""
        return [
            mt.to_dict() for mt in self.all_multi_tf_fvgs
            if mt.decision_fvg
        ]

    def cleanup_old(self, max_age_bars: int = 200):
        """Remove old broken FVGs to manage memory."""
        for tf, tracker in self.trackers.items():
            tracker.cleanup_old(max_age_bars)

        # Remove from our list too
        self.all_multi_tf_fvgs = [
            mt for mt in self.all_multi_tf_fvgs
            if mt.is_active or mt.decision_fvg
        ]

    def get_summary(self) -> dict:
        """Summary statistics for dashboard display."""
        active = [mt for mt in self.all_multi_tf_fvgs if mt.is_active]
        broken = [mt for mt in self.all_multi_tf_fvgs if mt.status == FVGStatus.BROKEN]
        decisions = [mt for mt in self.all_multi_tf_fvgs if mt.decision_fvg]

        by_tf = {}
        for tf in MULTI_TF_FVG_TIMEFRAMES:
            tf_fvgs = [mt for mt in self.all_multi_tf_fvgs if mt.timeframe == tf]
            by_tf[tf] = {
                "total": len(tf_fvgs),
                "active": len([m for m in tf_fvgs if m.is_active]),
                "broken": len([m for m in tf_fvgs if m.status == FVGStatus.BROKEN]),
                "bullish_active": len([m for m in tf_fvgs if m.is_active and m.fvg_type == FVGType.BULLISH]),
                "bearish_active": len([m for m in tf_fvgs if m.is_active and m.fvg_type == FVGType.BEARISH]),
            }

        return {
            "total_fvgs": len(self.all_multi_tf_fvgs),
            "active_fvgs": len(active),
            "broken_fvgs": len(broken),
            "decision_fvgs": len(decisions),
            "entry_signals": len(self.entry_signals),
            "by_timeframe": by_tf,
        }
